### PR TITLE
Ui changes

### PR DESCRIPTION
**Pull request by AnshulHedau**
Added bootstrap for responsiveness across different screen sizes

### CODE REVIEW

**Review by mohammedaz33m — COMMENTED** [review]
Hi, Anshul Hedau, 
Thanks a lot for your response. I am closing this issue for now & will approve once I review it

**Comment by AnshulHedau** [comment]
Sure, @mohammedaz33m 
Kindly add the label hacktoberfest-accepted to the PR's 
Thanks

**Comment by mohammedaz33m** [comment]
> Sure, @mohammedaz33m
> Kindly add the label hacktoberfest-accepted to the PR's
> Thanks

I have added the label.

**Comment by AnshulHedau** [comment]
image
Can u update the label for the PR's at the place I circled

**Pull request merged**
